// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkjixjxrobkkfhhkaedb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indraml4anhyb2Jra2ZoaGthZWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTUyMjMsImV4cCI6MjA1Nzk3MTIyM30.DioGopr8NogE4xHBHVt_FGn6QrSYzKbVPEQTiix6ioA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);